# Predictive Modeling - Decision Tree

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set(style="darkgrid")

# Function for displaying all columns
def display_all(df):
    with pd.option_context("display.max_rows", 1000): 
        with pd.option_context("display.max_columns", 1000): 
            display(df)

In [10]:
# Reading data 
trainX = pd.read_csv('data/trainX.csv')
trainY = pd.read_csv('data/trainY.csv')
validX = pd.read_csv('data/validX.csv')
validY = pd.read_csv('data/validY.csv')

print(trainX.shape, trainY.shape, validX.shape, validY.shape)
display_all(trainX.head(10).transpose())

(31647, 48) (31647, 1) (6782, 48) (6782, 1)

                       0    1   2     3   4    5    6    7     8     9
age                   36   56  46    41  38   33   43   61    36    47
default                0    0   0     0   0    0    0    0     0     0
balance                0  196   0  3426   0  839  429  938  2415  1152
housing                0    0   1     0   1    1    1    0     1     0
loan                   0    0   0     0   0    0    0    0     0     0
day                   17   19   5     1  20   28   27   15    22     7
duration             153  312  83   302  90  469  222  212    73   260
campaign               4    3   2     1   1    3    4    2     1    13
pdays                 -1   -1  -1   119  -1   -1   -1   92    86    -1
previous               0    0   0     5   0    0    0    5     4     0
job_admin.             0    0   0     0   0    0    1    0     0     0
job_blue-collar        0    0   1     0   1    0    0    0     0     0
job_entrepreneur       0    1   0     0   0    0    0    0     0     0
job_housemaid          0    0   0     0   0    0    0    0     0     1
job_management         0    0   0     1   0    0    0    0     1     0
job_retired            0    0   0     0   0    0    0    1     0     0
job_self-employed      0    0   0     0   0    0    0    0     0     0
job_services           0    0   0     0   0    0    0    0     0     0
job_student            0    0   0     0   0    0    0    0     0     0
job_technician         1    0   0     0   0    1    0    0     0     0
job_unemployed         0    0   0     0   0    0    0    0     0     0
job_unknown            0    0   0     0   0    0    0    0     0     0
marital_divorced       0    0   0     1   0    1    0    0     0     0
marital_married        0    1   1     0   1    0    1    1     1     1
marital_single         1    0   0     0   0    0    0    0     0     0
education_primary      0    0   0     0   0    0    0    0     0     0
education_secondary    0    1   1     0   1    0    1    1     0     1
education_tertiary     1    0   0     1   0    1    0    0     1     0
education_unknown      0    0   0     0   0    0    0    0     0     0
contact_cellular       0    1   0     1   0    0    0    1     0     0
contact_telephone      0    0   0     0   0    0    0    0     1     1
contact_unknown        1    0   1     0   1    1    1    0     0     0
month_apr              0    0   0     0   0    0    0    0     0     0
month_aug              0    0   0     0   0    0    0    0     0     0
month_dec              0    0   0     0   0    0    0    0     0     0
month_feb              0    0   0     0   0    0    0    0     0     0
month_jan              0    0   0     0   0    0    0    0     0     0
month_jul              0    0   0     0   0    0    0    0     0     1
month_jun              1    0   1     0   0    0    0    0     0     0
month_mar              0    0   0     0   0    0    0    0     0     0
month_may              0    0   0     0   1    1    1    0     0     0
month_nov              0    1   0     0   0    0    0    0     0     0
month_oct              0    0   0     1   0    0    0    1     1     0
month_sep              0    0   0     0   0    0    0    0     0     0
poutcome_failure       0    0   0     0   0    0    0    0     0     0
poutcome_other         0    0   0     0   0    0    0    0     1     0
poutcome_success       0    0   0     1   0    0    0    1     0     0
poutcome_unknown       1    1   1     0   1    1    1    0     0     1